# ✅ Auth section
[auth]
admin_email = "ogunbowaleadeola@gmail.com"
allowed_domains = ["buffalo.edu"]

# ✅ Labs section (multi-lab support)
[labs]
"buffalo.edu" = "Adelaiye-Ogala Lab"
"columbia.edu" = "Columbia Precision Lab"
"harvard.edu" = "Harvard AI Oncology Lab"
